utils/buffer/buffer.go
value.go
value_test.go

Please review the remove unsafe change.
This change removes uses of unsafe for deploying an aerospike client to the google app engine.

Remove unsafe

---

utils/buffer/buffer.go
value.go

previous didn't work on 32bit (I'm so sorry)
make sure it works ok on 32-bit (go playground):
http://play.golang.org/p/Hceoxd9J_h

Fix simpler method to find int size

---

batch_command_get.go

At present, BatchGet(policy BasePolicy, keys *[]Key, bins ...string) ([]Record, error) altogether ignores the |bins| argument. Looks like it's omitted in newBatchCommandGet(), and with this CL I'm seeing restrictions being correctly applied.

Fix: newBatchCommandGet() ignoring binNames restrictions

---

client_policy.go
connection.go
node.go
node_test.go

I have added a ```MaxIdle``` option to ClientPolicy to tackle the following problems:
Because the connection pool is a FIFO queue, and because the "tend" logic of updating
information about the cluster gets connection after connection from the pool every TendInterval slices,
there will be cases where lots of connections are unnecessarily "kept open" in the pool, depending on the client's TendInterval value (1s by default) and aerospike server's proto-fd-idle-ms (60s by default).
By default, once we manage to get more than 60 connections in the pool, the first 60 will probably never be closed, assuming no errors occur, even when there is no load at all for some time.
When some connection request peak is over, we will in most cases want to
close those connections after some time, and remove …

Added IdleTimeout to ClientPolicy to manage idle connections

---

node.go
node_test.go

Even on authentication failure, no errors are returned due to improper error handling.
This PR is an attempt to fix it.
The same problem may also occur when calling SetTimeout, but since it is not currently possible to test that and the fix is similar, I am including in the same PR.

Fixed error handling on authentication failure

---

admin_command.go
client.go
command.go
execute_task.go
info.go
node.go
node_test.go
security_test.go
tools/asinfo/asinfo.go

I realized that Node connectionCount is not decrement when connections don't return through PutConnection.
There is a possibility to block new connection if LimitConnectionsToQueueSize is true and connections have some problems.
This PR is an attempt to fix it.
I'm not sure whether the connection pool handling on Node.Refresh is correct or not...

Fixed invalid connection handling on node connections

---

README.md

Fix a typo in the README.md.
Also adds the related `go get` command.

Fix gopkg.in typo in README.md

---

recordset.go

The `Result` type contains a `Record` as a field. It's not embedded. If `Record` was embedded then it would be possible to reference all the fields of Record directly on Result. e.g. `result.Key` instead of `result.Record.Key`.
Also fixed the example, it needs an extra space indentation to be rendered correctly by godoc.

Small fixes to the (*Recordset).Results() comment

---

admin_policy.go
client.go
cluster.go
commit_policy.go
consistency_level.go
field_type.go
key.go
large_list.go
large_map.go
marshal.go
operation.go
role.go
user_roles.go

*These changes do not modify any behavior.*
I noticed that golint was giving a lot of warnings/notices, so I took a few seconds to get rid of some of them. Most changes are correcting comment formats and removing of unrequired else blocks.
I'm ignoring some notices (`grep -v`). The first (dot import) is a lot of work to get rid of, and not that important to the user. The second (caps) and third (Id>ID) would require breaking changes.
These golint notices are now left:
```
$ golint | grep -v "should not use dot imports" | grep -v "don't use ALL_CAPS in Go names" | grep -v "Id should be"
admin_command.go:57:6: exported type AdminCommand should have comment or be unexported
marshal.go:157:6: exported type SyncMap should have comment or be unexported
recordset.go:23:6: exported type Result …
```

Fix a bunch of golint notices.

---

connection.go

I noticed that the total read bytes count returned `*Connection.Read()` could be off from the actual number of read bytes when an error occurred. In some cases a net.Conn can read bytes (n>0) while also returning with an error (for example: EOF).

Fix *Connection.Read() total bytes count on error

---

read_command.go

I found and fixed a race condition.
The `readCommand` was storing a reference to the field `objectMappings` of the global var `objectMappings` (type `SyncMap`). It was using the reference for direct read access; thereby bypassing the SyncMap's getMapping method which adds a mutex lock/unlock around read/write operations on the map.
This fixes the race condition, but it comes with a cost (more mutex lock/unlock will occur). So you might not want to merge this in directly but instead first do a benchmark and/or improvements concerning performance.

Fix race condition on objectMappings map

---

cluster.go

Ran into some issues where we would get an index out of range because
make() was given a length of zero.
Thus the first time nodeArray is accessed it threw an index out
of range panic.
It was only happening a few seconds after starting the cluster, so
there might be a bit more of an elegant solution but I have not had
time to take a deeper look into it.
Most recent stacktrace (using an older version of the library):
panic: runtime error: index out of range
goroutine 71 [running]:
github.com/aerospike/aerospike-client-go.(*Cluster).removeNodesCopy(0xc208
7d4080, 0xc2d2a6cee8, 0x1, 0x1)
/usr/go/src/github.com/aerospike/aerospike-client-go/cluster.go:528 +0x54d
github.com/aerospike/aerospike-client-go.(*Cluster).removeNodes(0xc2087d40
80, 0xc2d2a6cee8, 0x1, 0x1) …

cluster: Fix index out of range in removeNodesCopy

---

tools/asinfo/asinfo.go

Keeping in line with the golang standard library, I removed the deeply-nested if/else calls and (since error handling was mostly if err -> die()) moved error handling out into a dieIfError function that optionally takes a series of callbacks .
I also noticed that sepLines wasn't actually implemented-- I threw that in as well, but I'm not entirely sure if the formatting is in line with the asinfo tool distributed with the aerospike tools package. Where this golang script works marvelously, the asinfo from the tools package just gives me `request to  %{host} : %{port}  returned error` on the same query. So I followed the help text here and just replaced newlines with semicolons.
Changing the number of semicolons per newline is bikeshedding incarnate, so just let me know which way that …

Refactor tools/asinfo to be more idiomatic golang

---

marshal.go

This fixes issue #114.
The problem was that we were caching information about structs and addressing them by their type name, and anonymous structs have no type name. This change addresses structs by their reflect.Type instead of their name.

marshal: fixed object mapping cache for anonymous structs (issue 114)

---

value.go

before change:
$ GOOS=linux GOARCH=386 go build .
./value.go:103: constant 9223372036854775807 overflows uint
after change:
$ GOOS=linux GOARCH=386 go build .

Don't use math.MaxInt64, it breaks 32-bit builds

---

marshal.go

Current PutObject implementation stores []byte as LIST aerospike type. That differs from non-reflection methods behavior

PutObject: handle blobs correctly

---

node.go

Hi there.
It seems that `connectionCount` is always invalid value when `LimitConnectionsToQueueSize` is false.

In case of LimitConnectionsToQueueSize is false, connectionCount is invalid

---

read_command_reflect.go

For GetObject() for
```go
struct {
Test int `as:"test"`
}
```
if bin 'test' not exists we get 'panic: reflect: call of reflect.Value.Type on zero Value'

Fix panic in GetObject() if all bins in results nil

---

client_policy.go
node_validator.go

Not common usecase. service.address set to 0.0.0.0 and some interfaces not visible beacuse of proxy or VPN. Initialising client takes forever.

Ignore hosts from other subnets

---

types/result_code.go

All the other constants are of the type `ResultCode`, so these should be as well.

minor: missing ResultCode types

---

command.go
docs/policies.md
policy.go

Hi,
This PR adds a `SleepMultiplier` field to `BasePolicy`, which can be used to define the multiplying factor for exponential backoff during retries. See #177 for more information.
Please review and merge.
Thanks,
Venil

Adds SleepMultiplier to BasePolicy for exponential backoff

---

cluster.go

Hi, @khaf .
Client version: v1.27.0 (1dc8cf203d24cd454e71ce40ab4cd0bf3112df90).
Server version: Aerospike Server CE :3.14.0
Sometimes happens panic occasionally when the Close function is called multiple times in parallel.
It seems that closing `tendChannel` is called twice.
Sample code is here:
```go
func main() {
client, err := aerospike.NewClient("127.0.0.1", 3000)
panicOnError(err)
defer client.Close()
Task(client)
// end
}
```
Traceback is here: (file path is simplified)
```
panic: close of closed channel
goroutine 4 [running]:
vendor/github.com/aerospike/aerospike-client-go.(*Cluster).Close(0xc42007afc0)
vendor/github.com/aerospike/aerospike-client-go/cluster.go:898 +0x5c
vendor/github.com/aerospike/aerospike-client-go.(*Client).Close(0xc42036b410) …
```

Sometimes finalizer for closing cluster happens panic

---

command.go

Hi, this fix was born from error log message ([caller string](https://github.com/aerospike/aerospike-client-go/blob/master/command.go#L1286)):
```text
command execution timed out on client: Exceeded number of retries. 
See `Policy.MaxRetries`. (last error: %!s(<nil>))
```
`%!s(<nil>)`  because  err var redefined [here](https://github.com/aerospike/aerospike-client-go/blob/master/command.go#L1309) for each loop iteration.
Looks like `socketTimeout` can't change between execution iterations and we can define him once.
With this fix resulting error message looks like this:
```
command execution timed out on client: Exceeded number of retries. 
See `Policy.MaxRetries`. (last error: No available connections to the node. 
Connection Pool was empty, and limited to certain number of connections.) …
```

Get socket timeout once per command execution

---

docs/policies.md
multi_policy.go

Hi, 
This fixes the default RecordQueueSize listed in the scan policy documentation, which currently says its value is 5000, but the code uses 50.
dave

fixing default RecordQueueSize in documentation

---

node.go

Hi,
this change updates `Node#Refresh` function to send `racks:` command based on `clientPolicy.RackAware` flag. There are two reasons behind it:
1. `racks:` won't be sent to older versions of `Aerospike` which don't support it. This will remove `received command racks, not registered` message from the log which is getting spammed by it otherwise.
2. `updateRackInfo` function [checks the state of the flag](https://github.com/aerospike/aerospike-client-go/blob/master/node.go#L232-L234) as well and doesn't use result of the command if it is not set.

Don't send racks: command if clientPolicy.RackAware is not set

---

client_reflect.go

fix: distinct error when empty slice is passed to BatchGetObjects

---

read_command_reflect.go

There is currently a bug happening when using `GetObject()`. See the following pseudo-code:
```go
type MyObject struct {
List []string
}
func testcase() {
var o1, o2 MyObject
o1.List = nil // the default is nil anyways
o2.List = []string{}
client.GetObject(nil, key, &o1)
client.GetObject(nil, key, &o2)
if len(o1.List) != len(o2.List) {
panic("BUG: slice was not set properly")
}
}
```
With the change proposed here the bug is fixed (the slice gets assigned); the assignment `f = ` there is currently doing nothing.
There do not seem to be unit tests for this function, otherwise I would have added a regression test; perhaps I can contribute something on a separate PR.

GetObject slices bug: assign result of the append

---

docs/policies.md

Hi,
This fix updates policy document to match the code.
- Removed `GenerationPolicy.DUPLICATE`
- Update `Expiration` Values

fix policy document
